# 开发环境 Docker Compose 配置
# 使用方式: docker-compose -f docker-compose.dev.yaml up
version: "3.8"

services:
  # MongoDB 数据库服务
  mongo:
    image: mongo:7.0
    container_name: evaluation-mongo-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: k765g6hj
      MONGO_INITDB_DATABASE: xiaojuSurvey
    ports:
      - "27017:27017"
    volumes:
      - mongo-dev-data:/data/db
      - mongo-dev-config:/data/configdb
    networks:
      - evaluation-dev-network

  # Redis 缓存服务
  redis:
    image: redis:7-alpine
    container_name: evaluation-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    networks:
      - evaluation-dev-network
    command: redis-server --appendonly yes

  # 开发环境不启动应用容器，使用本地开发
  # 仅启动依赖服务（MongoDB 和 Redis）

volumes:
  mongo-dev-data:
    driver: local
  mongo-dev-config:
    driver: local
  redis-dev-data:
    driver: local

networks:
  evaluation-dev-network:
    name: evaluation-dev-network
    driver: bridge