version: "3"

services:
  # MongoDB数据库
  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: k765g6hj
      MONGO_INITDB_DATABASE: xiaojuSurvey
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # 生产模式 - 使用Dockerfile构建
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      XIAOJU_SURVEY_MONGO_URL: mongodb://root:k765g6hj@mongo:27017/?authSource=admin
      XIAOJU_SURVEY_MONGO_AUTH_SOURCE: admin
      XIAOJU_SURVEY_MONGO_DB_NAME: xiaojuSurvey
      XIAOJU_SURVEY_JWT_SECRET: xiaojuSurveyJwtSecret
      XIAOJU_SURVEY_JWT_EXPIRES_IN: 8h
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: emojump.888
      NODE_ENV: production
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network: