version: "3.6"
services:
  # Redis缓存服务
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  xiaoju-survey:
    # 选择镜像版本：
    # slim版本 (推荐生产环境): xiaojusurvey/xiaoju-survey:1.3.3-slim
    # 完整版本 (推荐开发环境): xiaojusurvey/xiaoju-survey:1.3.3
    image: "xiaojusurvey/xiaoju-survey:1.3.3-slim" # 最新版本：https://hub.docker.com/r/xiaojusurvey/xiaoju-survey/tags
    container_name: xiaoju-survey
    restart: always
    ports:
      - "8080:8080" # API端口
    environment:
      XIAOJU_SURVEY_MONGO_URL: mongodb://root:k765g6hj@dbconn.sealoshzh.site:47633/?directConnection=true # 外部 MongoDB 连接
      XIAOJU_SURVEY_MONGO_AUTH_SOURCE: admin # MongoDB 认证数据库
      # Redis配置
      XIAOJU_SURVEY_REDIS_HOST: redis
      XIAOJU_SURVEY_REDIS_PORT: 6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AImodel_API_URL: ${AImodel_API_URL}
      AImodel_API_KEY: ${AImodel_API_KEY}
      AImodel_MODEL: ${AImodel_MODEL}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge