version: "3.6"
services:
  mongo:
    image: mongo:4
    container_name: xiaoju-survey-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin} # 默认使用系统的环境变量，如果没有则使用admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-123456} # 默认使用系统的环境变量，如果没有则使用123456
    ports:
      - "27017:27017" # 数据库端口
    volumes:
      - mongo-volume:/data/db # xiaoju-survey-data/db/data:/data/db
    networks:
      - xiaoju-survey

  xiaoju-survey:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xiaoju-survey
    restart: always
    ports:
      - "8080:80" # API端口
    environment:
      XIAOJU_SURVEY_MONGO_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:-admin}:${MONGO_INITDB_ROOT_PASSWORD:-123456}@xiaoju-survey-mongo:27017/admin?authSource=admin
      XIAOJU_SURVEY_MONGO_AUTH_SOURCE: admin
      XIAOJU_SURVEY_MONGO_DB_NAME: xiaoju_survey
    links:
      - mongo:mongo
    depends_on:
      - mongo
    networks:
      - xiaoju-survey

volumes:
  mongo-volume:

networks:
  xiaoju-survey:
    name: xiaoju-survey
    driver: bridge
