version: "3"

services:
  # MongoDB数据库
  mongo:
    image: mongo:7.0
    container_name: evaluation-mongo-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: k765g6hj
      MONGO_INITDB_DATABASE: xiaojuSurvey
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-dev:/data/db
    networks:
      - app-network-dev

  # 开发模式 - 直接挂载源码
  app-dev:
    image: node:18-alpine
    container_name: evaluation-app-dev
    working_dir: /app
    volumes:
      - ./server:/app/server
      - ./web:/app/web
    ports:
      - "3000:3000"  # 后端API
      - "8080:8080"  # 前端
    environment:
      XIAOJU_SURVEY_MONGO_URL: mongodb://root:k765g6hj@mongo:27017/?authSource=admin
      XIAOJU_SURVEY_MONGO_AUTH_SOURCE: admin
      XIAOJU_SURVEY_MONGO_DB_NAME: xiaojuSurvey
      NODE_ENV: development
    networks:
      - app-network-dev
    depends_on:
      - mongo
    command: >
      sh -c "
        echo '启动后端服务...' &&
        cd /app/server && npm install && npm run dev &
        echo '等待后端启动...' &&
        sleep 10 &&
        echo '启动前端服务...' &&
        cd /app/web && npm install && npm run dev --host
      "

volumes:
  mongo-data-dev:

networks:
  app-network-dev: