version: "3"

services:
  # Redis缓存服务（保留本地Redis）
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes

  # 生产模式 - 使用Dockerfile构建
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      XIAOJU_SURVEY_MONGO_URL: mongodb://root:k765g6hj@dbconn.sealoshzh.site:47633/?directConnection=true
      XIAOJU_SURVEY_MONGO_AUTH_SOURCE: admin
      XIAOJU_SURVEY_MONGO_DB_NAME: xiaojuSurvey
      XIAOJU_SURVEY_REDIS_HOST: redis
      XIAOJU_SURVEY_REDIS_PORT: 6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      XIAOJU_SURVEY_JWT_SECRET: xiaojuSurveyJwtSecret
      XIAOJU_SURVEY_JWT_EXPIRES_IN: 8h
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: emojump.888
      NODE_ENV: production
    depends_on:
      - redis
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network: