version: "3.6"
services:
  mongo:
    image: mongo:4
    container_name: xiaoju-survey-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7.4-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes --aof-use-rdb-preamble no
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  xiaoju-survey:
    build: .
    restart: always
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      XIAOJU_SURVEY_MONGO_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT:-27017}
      XIAOJU_SURVEY_MONGO_AUTH_SOURCE: ${XIAOJU_SURVEY_MONGO_AUTH_SOURCE}
      XIAOJU_SURVEY_MONGO_DB_NAME: ${XIAOJU_SURVEY_MONGO_DB_NAME}
      XIAOJU_SURVEY_REDIS_HOST: redis
      XIAOJU_SURVEY_REDIS_PORT: 6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AImodel_API_URL: ${AImodel_API_URL}
      AImodel_API_KEY: ${AImodel_API_KEY}
      AImodel_MODEL: ${AImodel_MODEL}
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
